### PR TITLE
rent logic added urls

### PR DESCRIPTION
**Pull request by laurajbarros**
I've created a function inside app.map.js that gets the BIN and does an API call to carto and fetches the matching URL for rent Logic. After doing it, the url is added to the rent-logic button. 
I've added translations to chinese and spanish and I changed some CSS so the new button (rent-logic) would look nice.

### CODE REVIEW

**Comment by clhenrick** [comment]
Thanks very much @laurajbarros I'll take a look soon.

**Comment by clhenrick** [comment]
@laurajbarros at a first glance your code seems to work correctly when a building address matches, though when it doesn't I've seen a couple cases where the BIN returned from the GeoClient API call matches a different address in the `bin_bbl_url` table. 

Examples:

- 55 Water Street, BK (BIN 3000019) => `https://rentlogic.com/building/2-main-street-brooklyn`

- One Metro Tech Center (BIN 3000350) => `https://rentlogic.com/building/81-willoughby-street-brooklyn`

But this seems to be more of an issue with the GeoClient API and am not sure if it's resolvable or not on our end. These are also not typical or residential addresses that someone would typically search for within this app. Did you happen to notice any odd address matches like this? I can also check with Yale.

Also, I think we should have the default URL for the "View Info at Rent Logic" button set to `https://rentlogic.com` so that if someone doesn't search for an address and skips ahead by clicking "When You Receive Your Rent History" that the button works. I'll go ahead and make that change.

Again, I appreciate your help!

**Comment by clhenrick** [comment]
note: made minor updates in a0de2dd on `laurajbarros-master` branch

**Comment by laurajbarros** [comment]
Hey Chris,

Thanks for your changes. No, i haven't found any issues on the addresses,
but testing now it is true. It is pulling from the api , (
https://chenrick.carto.com/api/v2/), so I guess it is indeed mapped wrongly
there. that is Rent's logic right?

Ok, thanks for the changes!

Laura

Laura Barros
Founder na Devinco
www.devinco.com.br
(21) 99452-1081
https://br.linkedin.com/in/laurajbarros

**Pull request merged**
